language: node_js
node_js:
 - "node"
install:
  - npm install -g pg
  - npm install -g codecov
  - npm install
after_success: npm run coverage
services:
  - postgresql
env:
  - NODE_ENV=TEST
  - TEST_DATABASE=postgres://postgres:@localhost:5432/community
before_script:
  - psql -c 'create database community;' -U postgres
  - npm run build:db
  # - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres
  # - node src/model/database/dbBuild.js postgres://postgres:postgres@127.0.0.1:5432/community
