language: node_js
node_js:
 - "node"
install:
  - npm install -g pg
  - npm install -g codecov
  - npm install
after_success: npm run coverage
services:
  - postgresql
env:
  - DB_CONFIG.database=postgres://postgres:postgres@localhost:5432/community
before_script:
  - psql -c 'create database community;' -U postgres
  # - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres
