language: node_js
node_js:
 - "node"
install:
  - npm install -g pg
  - npm install -g codecov
after_success: npm run coverage
services:
  - postgresql
env:
  - DB_CONFIG.database=postgres://127.0.0.1:5432/community
before_script:
  - node src/model/database/dbBuild.js
