language: node_js
node_js:
 - "node"
install:
  - npm install -g pg
  - npm install -g codecov
after_success: npm run coverage
services:
  - postgresql
env:
  - DB_CONFIG.database=postgres://postgres:postgres@localhost:5432/community
before_script:
  - NODE_ENV=test node src/model/database/dbBuild.js
